apiVersion: v1
kind: Service
metadata:
  name: api-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: api-{{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.api.port }}
      protocol: TCP
      name: http
  selector:
    app: api-{{ .Values.name }}
  type: LoadBalancer