apiVersion: v1
kind: ConfigMap
metadata:
  name: init-schema
data:
  init-schema.sql: |
    SELECT 'CREATE DATABASE canigowatchthis' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'canigowatchthis')\gexec

    \c canigowatchthis

    CREATE TABLE IF NOT EXISTS games (
        id SERIAL PRIMARY KEY,
        game_id TEXT NOT NULL,
        league TEXT NOT NULL,
        time TIME NOT NULL,
        UNIQUE (game_id, league)
    );

    CREATE TABLE IF NOT EXISTS subscriptions (
        id INT NOT NULL,
        mail TEXT NOT NULL,
        CONSTRAINT subscriptions_fk FOREIGN KEY (id) REFERENCES games (id)
    );