{{ if .Values.notifier.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    name: postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: postgres
  selector:
    name: postgres
  type: ClusterIP
{{ end }}