{{ if .Values.notifier.enabled }}
apiVersion: v1
data:
  postgres_password: {{ randAlphaNum 32 | b64enc | quote }}
kind: Secret
metadata:
  name: postgress-password
  namespace: {{ .Values.namespace }}
type: Opaque
{{ end }}
